theme: jekyll-remote-theme
title: Ivan CORDOBA
logo : /assets/Profil_photo_3.jpg
description :  Curriculum vitae and Portfolio
description : E-mail ivancordoba93@gmail.com
remote_theme: pages-themes/minimal@v0.2.0
