theme: jekyll-remote-theme
title: Iván Córdoba Sánchez
logo : /assets/Profil_photo_4.jpg
description :  Curriculum vitae and Portfolio
description : E-mail ivancordoba93@gmail.com
remote_theme: pages-themes/minimal@v0.2.0
